import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const projectRoot = path.resolve(__dirname, '..');

const packageJsonPath = path.join(projectRoot, 'package.json');
const targetPath = path.join(projectRoot, 'src', 'app', 'app-version.ts');

const packageJson = JSON.parse(readFileSync(packageJsonPath, 'utf8'));
const version = String(packageJson.version || '0.0.0');
const commitSha =
  process.env.CF_PAGES_COMMIT_SHA ||
  process.env.GITHUB_SHA ||
  process.env.SOURCE_VERSION ||
  '';
const shortSha = commitSha ? commitSha.slice(0, 7) : '';
const buildVersion = shortSha ? `${version}+${shortSha}` : version;

const content = `// Auto-generated by scripts/write-version.mjs\nexport const APP_VERSION = '${buildVersion}';\n`;
writeFileSync(targetPath, content, 'utf8');
